### ISSUE TITLE
Parser Not Working

### ISSUE THREAD

**Issue by iampyrex** [endofzero/Minecraft-Logparser#22]
I run the injection and I get this:

 ./commands.php inject

Injection Counts
Log Lines: 11180481
Injections: 0
Duplicates: 0
Errors: 0
Cleared Master Log

**Comment by endofzero** [comment]
Looks to be reading the logs correctly.

I have noticed that on line 124 of the command.php, year is hardcoded to 2011, you probably need to change it as I have items being ignored.

// If year isn't the first 4, then ignore the line (usually java errors [SEVERE] error is still caught
if (substr($value,0,4)==$year){

**Comment by iampyrex** [comment]
That fixed it, but this thing needs some serious work.  It's not parsing my 1.4.7 logs properly.  Not even picking up chat.

**Comment by endofzero** [comment]
I can understand that, my last commit before these was May 10, 2011... 

You are more than welcome to fork it and update it to work with the latest version. 
I don't play much Minecraft nowadays, so I've not had much interest in the upkeep of this code.
